- name: Initiate Virtualenv
  become: true
  pip: virtualenv="{{ app_dir }}/{{ app_name }}/api/venv" virtualenv_command="/usr/bin/python3 -m venv" requirements={{ app_dir }}/{{ app_name }}/api/requirements.txt

- name: Initiate Data Directory
  become: true
  file: path={{ app_dir }}/data owner={{ app_user }} group={{ app_group }} state=directory

- name: Replace Application Home Execution Script
  become: true
  replace: path={{ app_dir }}/{{ app_name }}/api/run_dev.sh regexp=__APP-HOME__ replace={{ app_dir }}

- name: Replace Application Home Configuration
  become: true
  replace: path={{ app_dir }}/{{ app_name }}/api/config/development.py regexp=__APP-HOME__ replace={{ app_dir }}

- name: Replace Application Secret
  become: true
  replace: path={{ app_dir }}/{{ app_name }}/api/config/development.py regexp=__PASSWORD__ replace={{ app_secret }}

- name: Chown Application Directory
  become: true
  file: dest={{ app_dir }} owner={{ app_user }} group={{ app_group }} recurse=yes

- name: Gunicorn Supervisord Configuration 
  become: true
  template: src=examnow.conf.j2 dest=/etc/supervisord.d/{{ app_name }}.ini

- name: Set Selinux Permission 
  become: true
  command: setsebool -P httpd_can_network_connect 1

- name: Restart Supervisord
  become: true
  service: name=supervisord state=restarted
  notify:
    - restart nginx

