- name: System Software Install
  become: true
  yum: name={{ item }} state=present
  with_items :
    - python3
    - python3-devel
    - firewalld
    - epel-release
    - openssl
    - supervisor

- name: Add Group 
  become: true
  group: name={{ app_group }} state=present

- name: Add User 
  become: true
  user: name={{ app_user }} shell=/bin/bash group={{ app_group }} append=yes

- name: Enable firewall
  become: true
  service: name=firewalld state=started

- name: Open API Server Port
  become: true
  firewalld: port={{ app_api_port }}/tcp state=enabled

- name: Open Examnow Application Port
  become: true
  firewalld: port={{ app_port }}/tcp state=enabled